// Generated by @opencode-ai/httpapi-codegen. Do not edit.
import { Effect, Schema } from "effect"
import { Sse } from "effect/unstable/encoding"
import { HttpClientError } from "effect/unstable/http"
import { HttpApi, HttpApiClient, HttpApiGroup } from "effect/unstable/httpapi"
import {
  SessionsList,
  SessionsCreate,
  SessionsGet,
  SessionsSwitchAgent,
  SessionsSwitchModel,
  SessionsPrompt,
} from "@opencode-ai/server/groups/session-endpoints"
import { ClientError } from "./client-error"

const Api = HttpApi.make("generated").add(
  HttpApiGroup.make("sessions")
    .add(SessionsList)
    .add(SessionsCreate)
    .add(SessionsGet)
    .add(SessionsSwitchAgent)
    .add(SessionsSwitchModel)
    .add(SessionsPrompt),
)

type RawClient = HttpApiClient.ForApi<typeof Api>

const mapClientError = <E,>(error: E) =>
  HttpClientError.isHttpClientError(error) || Schema.isSchemaError(error) || Sse.Retry.is(error)
    ? new ClientError({ cause: error })
    : error

type Endpoint0_0Request = Parameters<RawClient["sessions"]["list"]>[0]
type Endpoint0_0Input = {
  readonly workspace?: Endpoint0_0Request["query"]["workspace"]
  readonly limit?: Endpoint0_0Request["query"]["limit"]
  readonly order?: Endpoint0_0Request["query"]["order"]
  readonly search?: Endpoint0_0Request["query"]["search"]
  readonly directory?: Endpoint0_0Request["query"]["directory"]
  readonly project?: Endpoint0_0Request["query"]["project"]
  readonly subpath?: Endpoint0_0Request["query"]["subpath"]
  readonly cursor?: Endpoint0_0Request["query"]["cursor"]
}
const Endpoint0_0 = (raw: RawClient["sessions"]) => (input?: Endpoint0_0Input) =>
  raw["list"]({
    query: {
      workspace: input?.workspace,
      limit: input?.limit,
      order: input?.order,
      search: input?.search,
      directory: input?.directory,
      project: input?.project,
      subpath: input?.subpath,
      cursor: input?.cursor,
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint0_1Request = Parameters<RawClient["sessions"]["create"]>[0]
type Endpoint0_1Input = {
  readonly id?: Endpoint0_1Request["payload"]["id"]
  readonly agent?: Endpoint0_1Request["payload"]["agent"]
  readonly model?: Endpoint0_1Request["payload"]["model"]
  readonly location?: Endpoint0_1Request["payload"]["location"]
}
const Endpoint0_1 = (raw: RawClient["sessions"]) => (input?: Endpoint0_1Input) =>
  raw["create"]({
    payload: { id: input?.id, agent: input?.agent, model: input?.model, location: input?.location },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint0_2Request = Parameters<RawClient["sessions"]["get"]>[0]
type Endpoint0_2Input = { readonly sessionID: Endpoint0_2Request["params"]["sessionID"] }
const Endpoint0_2 = (raw: RawClient["sessions"]) => (input: Endpoint0_2Input) =>
  raw["get"]({ params: { sessionID: input.sessionID } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint0_3Request = Parameters<RawClient["sessions"]["switchAgent"]>[0]
type Endpoint0_3Input = {
  readonly sessionID: Endpoint0_3Request["params"]["sessionID"]
  readonly agent: Endpoint0_3Request["payload"]["agent"]
}
const Endpoint0_3 = (raw: RawClient["sessions"]) => (input: Endpoint0_3Input) =>
  raw["switchAgent"]({ params: { sessionID: input.sessionID }, payload: { agent: input.agent } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint0_4Request = Parameters<RawClient["sessions"]["switchModel"]>[0]
type Endpoint0_4Input = {
  readonly sessionID: Endpoint0_4Request["params"]["sessionID"]
  readonly model: Endpoint0_4Request["payload"]["model"]
}
const Endpoint0_4 = (raw: RawClient["sessions"]) => (input: Endpoint0_4Input) =>
  raw["switchModel"]({ params: { sessionID: input.sessionID }, payload: { model: input.model } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint0_5Request = Parameters<RawClient["sessions"]["prompt"]>[0]
type Endpoint0_5Input = {
  readonly sessionID: Endpoint0_5Request["params"]["sessionID"]
  readonly id?: Endpoint0_5Request["payload"]["id"]
  readonly prompt: Endpoint0_5Request["payload"]["prompt"]
  readonly delivery?: Endpoint0_5Request["payload"]["delivery"]
  readonly resume?: Endpoint0_5Request["payload"]["resume"]
}
const Endpoint0_5 = (raw: RawClient["sessions"]) => (input: Endpoint0_5Input) =>
  raw["prompt"]({
    params: { sessionID: input.sessionID },
    payload: { id: input.id, prompt: input.prompt, delivery: input.delivery, resume: input.resume },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

const adaptGroup0 = (raw: RawClient["sessions"]) => ({
  list: Endpoint0_0(raw),
  create: Endpoint0_1(raw),
  get: Endpoint0_2(raw),
  switchAgent: Endpoint0_3(raw),
  switchModel: Endpoint0_4(raw),
  prompt: Endpoint0_5(raw),
})

export const make = (options?: { readonly baseUrl?: URL | string }) =>
  HttpApiClient.make(Api, options).pipe(Effect.map((raw) => ({ sessions: adaptGroup0(raw["sessions"]) })))
